version: '3'

services:
  mysql-development:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: helloworld
      MYSQL_DATABASE: testapp
    ports:
      - '3308:3306'
    volumes:
      - './config/my.conf:/etc/mysql/conf.d/config-file.cnf'
      - './data:/var/lib/mysql:rw'
  admin:
    image: adminer
    ports:
      - '8080:8080'
